export const GITHUB_FINDER_TYPES = {
  SET_USERS: 'SET_USERS',
  SET_USER: 'SET_USER',
  SET_REPOS: 'SET_REPOS',
  SET_LOADING: 'SET_LOADING',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
  SHOW_CLEAR_BTN: 'SHOW_CLEAR_BTN',
  HIDE_CLEAR_BTN: 'HIDE_CLEAR_BTN',
};
